#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.servers_sources, "*.cpp")

SConscript("dummy/SCsub")
# /*<<----- VEYA_COOKER: no Forward+/Mobile renderer, GPU effects or preview shaders. */
if env["veya_cooker"]:
    # RenderingDevice's data API still references the CPU SPIR-V reflection library.
    SConscript("renderer_rd/spirv-reflect/SCsub")
else:
    SConscript("renderer_rd/SCsub")
# /*>>----- VEYA_COOKER */
SConscript("storage/SCsub")
