#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_gltf = env_modules.Clone()

# Godot source files

env_gltf.add_source_files(env.modules_sources, "*.cpp")
env_gltf.add_source_files(env.modules_sources, "structures/*.cpp")

SConscript("extensions/SCsub")

# /*<<----- VEYA_COOKER: retain native format importer; exclude external DCC runners and UI. */
if env["veya_cooker"]:
    env_gltf.add_source_files(env.modules_sources, "editor/editor_scene_importer_gltf.cpp")
elif env.editor_build:
    env_gltf.add_source_files(env.modules_sources, "editor/*.cpp")
# /*>>----- VEYA_COOKER */
